/*========================================================================*/
/* NOM DU FICHIER  : mib_administration_data.h							  */
/*========================================================================*/
/* Compilateur     : GCC                                                  */
/* Linking locator : GCC                                                  */
/* Formatter       : GCC                                                  */
/* Auteur          : CM                                                   */
/* Date			   : 30/05/2007											  */
/* Libelle         : NET-SNMP:											  */
/* Projet          : WRM100                                               */
/* Indice          : BE019                                                */
/*========================================================================*/
/* Historique      :                                                      */
/*
 * Note: this file originally auto-generated by mib2c using
 *         mib2c.sodielec_format.conf, v1.0 Juin 2006
 * Version: PC_SOUS_LINUX: 0, CARTE_EVAL: 0 [oui(1), non(0)]
 * Date: Mon Jun 12 10:39:44 2006
 */
//BE019 16/03/2010 CM
// - CREATION source basée sur SDVB200 BE373
/*========================================================================*/

#ifdef MIB_ADMINISTRATION_DATA_H
#define MIB_ADMINISTRATION_DATA_H_EXT
#else
#define MIB_ADMINISTRATION_DATA_H_EXT extern
#endif

/** Déclarations de fonctions */
/** ** for MIB Tree       */
char * captureString_administration(int, WriteMethod **);
long captureInt_administration(int, WriteMethod **);

/** ** for Tables         */
char * captureString_evtV1configTable(int, int, WriteMethod **);
long captureInt_evtV1configTable(int, int, WriteMethod **);
char * captureString_evtV1PrototrapTable(int, int, WriteMethod **);
long captureInt_evtV1PrototrapTable(int, int, WriteMethod **);

void initdata_mib_administration(void);

#define EVTV1PROTOTRAPTABLE_LINES	5

/** ** for MIB Tree       */
#define EQUINFOV1NOM	1
#define EQUINFOV1LOCALISATION	2
#define EQUINFOV1ID	3
#define MGMTV1REEMISSIONTRAP	4
#define MGMTV1SIGNEVIECMD	5
#define MGMTV1SIGNEVIECYCLE	6
#define MGMTV1AUTORISATIONTRAP	7

/** ** for Tables         */
#define EVTV1CFGINDEX	1
#define EVTV1CFGEQUIPEMENT	2
#define EVTV1CFGID	3
#define EVTV1CFGDESCRIPTION	4
#define EVTV1CFGNIVEAUGRAVITE	5
#define EVTV1CFGACTION	6
#define EVTV1CFGTYPE	7
#define EVTV1PROTOTRAPINDEX	8
#define EVTV1PROTOTRAPNIVEAUGRAVITE	9
#define EVTV1PROTOTRAPCYCLE	10
#define EVTV1PROTOTRAPNOMBRE	11
#define ALARMEV1INDEX	12
#define ALARMEV1ID	13
#define ALARMEV1VALEUR	14
#define ALARMEV1EQUIPEMENT	15
#define ALARMEV1STATUT	16
#define ALARMEV1DATE	17
#define ALARMEV1HEURE	18
#define ALARMEV1ACQUIT	19




