/*========================================================================*/
/* NOM DU FICHIER  : mib_sodielecV2_data.h								  */
/*========================================================================*/
/* Compilateur     : GCC                                                  */
/* Linking locator : GCC                                                  */
/* Formatter       : GCC                                                  */
/* Auteur          : CM                                                   */
/* Date			   : 30/05/2007											  */
/* Libelle         : NET-SNMP:											  */
/* Projet          : WRM100                                               */
/* Indice          : BE000                                                */
/*========================================================================*/
/* Historique      :                                                      */
/*
 * Note: this file originally auto-generated by mib2c using
 *         mib2c.sodielec_format.conf, v1.0 Juin 2006
 * Version: PC_SOUS_LINUX: 0, CARTE_EVAL: 0 [oui(1), non(0)]
 * Date: Mon Jun 12 10:32:20 2006
 */
/*========================================================================*/

#ifdef MIB_SODIELECV2_DATA_H
#define MIB_SODIELECV2_DATA_H_EXT
#else
#define MIB_SODIELECV2_DATA_H_EXT extern
#endif

/** Déclarations de fonctions */
/** ** for MIB Tree       */
char * captureString_sodielecV2(int, WriteMethod **);
long captureInt_sodielecV2(int, WriteMethod **);

/** ** for Tables         */



/** ** for MIB Tree       */
#define INFOCONSTRUCTEUR	1
#define INFOTELEPHONE	2
#define INFOSITE	3

/** ** for Tables         */
