/*========================================================================*/
/* NOM DU FICHIER  : mib_sodielecV2.h									  */
/*========================================================================*/
/* Compilateur     : GCC                                                  */
/* Linking locator : GCC                                                  */
/* Formatter       : GCC                                                  */
/* Auteur          : CM                                                   */
/* Date			   : 30/05/2007											  */
/* Libelle         : NET-SNMP:											  */
/* Projet          : WRM100                                               */
/* Indice          : BE000                                                */
/*========================================================================*/
/* Historique      :                                                      */
/*
 * Note: this file originally auto-generated by mib2c using
 *         mib2c.sodielec_format.conf, v1.0 Juin 2006
 * Version: PC_SOUS_LINUX: 0, CARTE_EVAL: 0 [oui(1), non(0)]
 * Date: Mon Jun 12 10:35:48 2006
 */
/*========================================================================*/

#include "mibdefs.h"

/** To use 'header_generic', we need the util_funcs module */
config_require(util_funcs)


/*_______IV  - PROTOTYPES IMPORTES _____________________MODULE______________*/
void init_mib_sodielecV2(void);

/** ** for MIB Tree       */
FindVarMethod var_sodielecV2;

/** ** for Tables         */
