/*========================================================================*/
/* NOM DU FICHIER  : mib_administration.h								  */
/*========================================================================*/
/* Compilateur     : GCC                                                  */
/* Linking locator : GCC                                                  */
/* Formatter       : GCC                                                  */
/* Auteur          : CM                                                   */
/* Date			   : 30/05/2007											  */
/* Libelle         : NET-SNMP:											  */
/* Projet          : WRM100                                               */
/* Indice          : BE019                                                */
/*========================================================================*/
/* Historique      :                                                      */
/*
 * Note: this file originally auto-generated by mib2c using
 *         mib2c.sodielec_format.conf, v1.0 Juin 2006
 * Version: PC_SOUS_LINUX: 0, CARTE_EVAL: 0 [oui(1), non(0)]
 * Date: Mon Jun 12 10:39:44 2006
 */
//BE019 16/03/2010 CM
// - CREATION source basée sur SDVB200 BE373
/*========================================================================*/

#include "mibdefs.h"

/** To use 'header_generic', we need the util_funcs module */
config_require(util_funcs)


/*_______IV  - PROTOTYPES IMPORTES _____________________MODULE______________*/
void init_mib_administration(void);

/** ** for MIB Tree       */
FindVarMethod var_administration;
WriteMethod write_mgmtV1ReemissionTrap;
WriteMethod write_mgmtV1SigneVieCmd;
WriteMethod write_mgmtV1SigneVieCycle;
WriteMethod write_mgmtV1AutorisationTrap;

/** ** for Tables         */
FindVarMethod var_evtV1configTable;
FindVarMethod var_evtV1PrototrapTable;
FindVarMethod var_alarmeV1Table;
WriteMethod write_evtV1cfgNiveauGravite;
WriteMethod write_evtV1cfgAction;
WriteMethod write_evtV1PrototrapCycle;
WriteMethod write_evtV1PrototrapNombre;
WriteMethod write_alarmeV1Acquit;
